### PR TITLE
[KARAF-5691] WIP: Add Http Servlet Filter Collector

### PR DESCRIPTION
**Pull request by fpapon**
This is a first proposal for discussing.

Can you review please ?

### CODE REVIEW

**Comment by jbonofre** [comment]
@fpapon is it still a WIP or can I start the review ?

**Comment by fpapon** [comment]
@jbonofre yes it still a WIP and I have 2 problems :

- when update the config properties file and the bundle reload the conf, the Jetty servlet crash
- the context path define in the config properties file only work with "/"root pattern

Any idea ?

**Comment by fpapon** [comment]
You can review but I have one problem, the filter is bind by the http service but is not registred with the matching servlet.

Any idea ?

**Comment by jbonofre** [comment]
I gonna test it but it should work with the fixes we did on PAX Web.

**Comment by jbonofre** [comment]
Replace by #187

**Pull request closed without merging**
