### PR TITLE
[KARAF-6983] Add property "replaceDotsByUnderscores" to the configura…

### PR DESCRIPTION
**Pull request by paulsp**
[KARAF-6983] Add property "replaceDotsByUnderscores" to the configuration file

- Create the org.apache.karaf.decanter.marshaller.json.cfg for the JsonMarshaller
- Add property "replaceDotsByUnderscores" with the default value to the config file
- Add unit tests for the property
- Add the config file to the assembly

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jbonofre** [comment]
I'm not sure about this PR as the purpose is to have the config file as optional for marshaller (most of users don't have to change it). Let me think about that.

**Comment by paulsp** [comment]
JB,  I found this configuration property in the source code while configuring Alerting rules and noticed the rules were not catching events.  The events originated from decanter-collector-oshi and the field names contains one or more dots. I was using decanter-appender-file with JSON formatting to identify the field names, which resulted in using the wrong field name.  Only after digging into the source code did I find the property. 

The option to replace the dot with an underscore was added in v2.1.0 by [KARAF-5793] and that was to accommodate changes to ElasticSearch. The title of the issue includes the phrase "Provide an option replace", but nowhere outside of the issue is the property documented.

The point of this PR is to make the property visible within the configuration files, even if 99% of the user base never changed the property value.

**Comment by jbonofre** [comment]
@paulsp yes, I understand, and I think it makes sense. It's more a "documentation" purpose.

**Comment by paulsp** [comment]
@jbonofre What is the status of this request, specifically will the request be merged?

**Comment by jbonofre** [comment]
@paulsp I agree to merge it. I will do it ! Thanks !

**Pull request merged**
