### PR TITLE
Bulk indexing for elasticsearch appender, switch to Apache Johnzon for JSON handling, testcases added

### PR DESCRIPTION
**Pull request by salyh**
- Bulk indexing for elasticsearch appender
- Switch to Apache Johnzon for JSON handling
- Testcases added
- Elasticsearch updated to 1.4.4
- Minor other fixes

### CODE REVIEW

**Comment by ANierbeck** [comment]
Could not find artifact org.apache.johnzon:johnzon-mapper:jar:0.7-incubating in central, 
obviously version 0.6 is available from central, but not this one :/

**Comment by salyh** [comment]
0.7 will be released soon, sorry. can you change the deps to 0.6 or should i do it?

**Comment by salyh** [comment]
commit e7756b4 replaces johnzon 0.7 with 0.6 because 0.7 is not yet released

**Comment by ANierbeck** [comment]
applied to master, thanks for providing :)

**Pull request merged**
