### PR TITLE
[KARAF-6117] Add the split parser

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by fpapon** [comment]
@jbonofre there is an existing `IdentifyParser` in the api module, should we move it here?

https://github.com/apache/karaf-decanter/tree/master/api/src/main/java/org/apache/karaf/decanter/impl/parser

**Comment by jbonofre** [comment]
Let me do a new pass anyway, adding itests.

**Comment by fpapon** [comment]
Agree and what I have in mind is to move the default `IdentityParser` into the new `parser` module.
Thoughts?

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
@fpapon ah ok, catcha. It makes sense, as we have for the `raw` marshaller. I will.

**Pull request merged**
